@baseUrl = http://localhost:3000

### Try to login an unknow user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"unknown",
    "password":"admin"
}

### Login the default admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"admin@admin.com",
    "password":"Admin1234"
}

### Login with a user that does not exist
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"manager",
    "password":"manager"
}

### Try to register
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"testRegister",
    "email":"test@register.com",
    "password":"12345678",
    "passwordConfirm":"12345678"
}

### try Login with a user that just registered
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"test@register.com",
    "password":"12345678"
}
