@baseUrl = http://localhost:3000

### Try to login an unknow user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "loginUser":"unknown",
    "password":"admin"
}

### Login the default admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "loginUser":"admin@admin.com",
    "password":"Admin1234"
}

### Login with a user that does not exist
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "loginUser":"manager",
    "password":"manager"
}

### Try to register
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"testRegister",
    "email":"test@register.com",
    "password":"12345678",
    "passwordConfirm":"12345678"
}

### Try to register with an existing email
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"sdkjnfisnfg",
    "email":"test@register.com",
    "password":"12345678",
    "passwordConfirm":"12345678"
}

### Try to register with an existing username
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"testRegister",
    "email":"skjfn@kjhb.com",
    "password":"12345678",
    "passwordConfirm":"12345678"
}

### try Login with a user that just registered
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "loginUser":"test@register.com",
    "password":"12345678"
}

### try Login with username 
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "loginUser":"testRegister",
    "password":"12345678"
}
